# Generated by Django 3.2.5 on 2021-07-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
